---
- name: Configurar master K3s
  hosts: master
  become: true
  tasks:
    - name: Instalar K3s no master
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server \
          --token={{ k3s_token }} \
          --disable traefik \
          --disable servicelb \
          --flannel-backend=host-gw \
          --kube-controller-manager-arg="bind-address=0.0.0.0" \
          --kube-scheduler-arg="bind-address=0.0.0.0" \
          --kube-proxy-arg="metrics-bind-address=0.0.0.0" \
          --node-taint "node-role.kubernetes.io/master=true:NoSchedule"
      args:
        creates: /usr/local/bin/k3s

    - name: Esperar K3s iniciar
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        delay: 5
        timeout: 300

    - name: Obter kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./kubeconfig
        flat: yes

- name: Configurar workers K3s
  hosts: workers
  become: true
  tasks:
    - name: Instalar K3s worker
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['k3s-master']['ansible_host'] }}:6443 K3S_TOKEN={{ k3s_token }} sh -
      args:
        creates: /usr/local/bin/k3s
