apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    created_by: "urbancompasspony"
spec:
  containers:
    - name: hello
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
            echo "Hello from K3s!";
            sleep 3600;
          done
