---
- name: Remover completamente o cluster K3s
  hosts: all
  become: true
  tasks:
    - name: Parar e remover o K3s em master
      shell: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: yes
      when: inventory_hostname in groups['master']

    - name: Parar e remover o K3s-agent em workers
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: yes
      when: inventory_hostname in groups['workers']

    - name: Remover diretórios K3s
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rancher
        - /var/lib/rancher
        - /var/log/pods
        - /var/lib/kubelet

    - name: Remover arquivos kubeconfig
      file:
        path: /root/.kube
        state: absent
      ignore_errors: yes

    - name: Reiniciar todos os nós
      reboot:
